"""
app.py
Streamlit UI for FinAgent - chat + dashboard + alerts + goals.
Run with: streamlit run app.py
"""

import streamlit as st
import pandas as pd
import plotly.express as px

from data_gen import generate_transactions, inject_anomalies, generate_live_batch
from agent import FinAgent

st.set_page_config(page_title="MYFY.AI", page_icon="💰", layout="wide")


# ---------------------------------------------------------------------------
# Session state / data init
# ---------------------------------------------------------------------------
if "transactions" not in st.session_state:
    df = generate_transactions(500, seed=42)
    df = inject_anomalies(df, n_anomalies=8, seed=7)
    st.session_state.transactions = df

if "agent" not in st.session_state:
    st.session_state.agent = FinAgent(st.session_state.transactions)

if "chat_history" not in st.session_state:
    st.session_state.chat_history = []

if "alerts" not in st.session_state:
    st.session_state.alerts = []


# ---------------------------------------------------------------------------
# Sidebar
# ---------------------------------------------------------------------------
st.sidebar.title("💰 MYFY.AI")
st.sidebar.caption("AI-powered personal finance assistant — ML + RAG + Agents")

if st.sidebar.button("🔄 Simulate new live transactions"):
    new_batch = generate_live_batch(n=5)
    st.session_state.transactions = pd.concat(
        [st.session_state.transactions, new_batch], ignore_index=True
    )
    st.session_state.agent = FinAgent(st.session_state.transactions)
    st.sidebar.success(f"Added {len(new_batch)} new live transactions.")

if st.sidebar.button("📡 Run proactive monitoring check"):
    new_alerts = st.session_state.agent.run_scheduled_check()
    st.session_state.alerts.extend(new_alerts)
    st.sidebar.success(f"Found {len(new_alerts)} new alert(s).")

df = st.session_state.transactions
agent = st.session_state.agent

tab1, tab2, tab3, tab4 = st.tabs(["💬 Chat", "📊 Dashboard", "🔔 Alerts", "🎯 What-If"])


# ---------------------------------------------------------------------------
# TAB 1: Chat
# ---------------------------------------------------------------------------
with tab1:
    st.subheader("Ask FinAgent about your finances")
    st.caption(
        "Try: \"How much did I spend on dining?\", \"Should I refinance my loan?\", "
        "\"What will I spend next month?\", \"Any unusual transactions?\", "
        "\"What is the 50/30/20 budgeting rule?\""
    )

    query = st.text_input("Your question", key="query_input")
    if st.button("Ask") and query:
        result = agent.ask(query)
        st.session_state.chat_history.append((query, result))

    for q, result in reversed(st.session_state.chat_history):
        with st.chat_message("user"):
            st.write(q)
        with st.chat_message("assistant"):
            st.write(f"**[routed to: {result['intent']}]**")
            st.write(result["answer"])
            data = result["data"]
            if isinstance(data, pd.DataFrame) and not data.empty:
                st.dataframe(data, use_container_width=True)


# ---------------------------------------------------------------------------
# TAB 2: Dashboard
# ---------------------------------------------------------------------------
with tab2:
    st.subheader("Spending Overview")

    col1, col2, col3 = st.columns(3)
    total_spend = df[df["type"] == "debit"]["amount"].sum()
    total_income = df[df["type"] == "credit"]["amount"].sum()
    col1.metric("Total Spend", f"₹{total_spend:,.0f}")
    col2.metric("Total Income", f"₹{total_income:,.0f}")
    col3.metric("Net", f"₹{total_income - total_spend:,.0f}")

    cat_spend = df[df["type"] == "debit"].groupby("category")["amount"].sum().reset_index()
    fig1 = px.pie(cat_spend, names="category", values="amount", title="Spending by Category")
    st.plotly_chart(fig1, use_container_width=True)

    df_time = df.copy()
    df_time["date"] = pd.to_datetime(df_time["date"])
    df_time["month"] = df_time["date"].dt.to_period("M").astype(str)
    monthly = df_time[df_time["type"] == "debit"].groupby("month")["amount"].sum().reset_index()
    fig2 = px.line(monthly, x="month", y="amount", title="Monthly Spending Trend", markers=True)
    st.plotly_chart(fig2, use_container_width=True)

    st.subheader("All Transactions")
    st.dataframe(df.sort_values("date", ascending=False), use_container_width=True)


# ---------------------------------------------------------------------------
# TAB 3: Alerts
# ---------------------------------------------------------------------------
with tab3:
    st.subheader("Proactive Alerts")
    st.caption("Generated by the scheduled monitoring agent — click the sidebar button to run a new check.")
    if not st.session_state.alerts:
        st.info("No alerts yet. Run a proactive monitoring check from the sidebar.")
    for alert in reversed(st.session_state.alerts):
        if alert.startswith("[ANOMALY]"):
            st.error(alert)
        else:
            st.warning(alert)


# ---------------------------------------------------------------------------
# TAB 4: What-If Simulator
# ---------------------------------------------------------------------------
with tab4:
    st.subheader("What-If Scenario Simulator")

    categories = df[df["type"] == "debit"]["category"].unique().tolist()
    sel_cat = st.selectbox("Category to adjust", categories)
    pct_change = st.slider("Change spending by (%)", -50, 50, 0)

    current_spend = df[(df["category"] == sel_cat) & (df["type"] == "debit")]["amount"].sum()
    new_spend = current_spend * (1 + pct_change / 100)
    monthly_diff = (current_spend - new_spend) / 6  # rough monthly impact over 6-month window

    col1, col2 = st.columns(2)
    col1.metric(f"Current {sel_cat} spend (6mo)", f"₹{current_spend:,.0f}")
    col2.metric(f"Projected {sel_cat} spend (6mo)", f"₹{new_spend:,.0f}", delta=f"₹{new_spend - current_spend:,.0f}")

    st.write(f"Estimated monthly savings/cost from this change: **₹{monthly_diff:,.0f}/month**")

    st.divider()
    st.subheader("Savings Goal Tracker")
    goal_name = st.text_input("Goal name", "Trip Fund")
    target = st.number_input("Target amount (₹)", min_value=0, value=50000, step=1000)
    saved = st.number_input("Amount saved so far (₹)", min_value=0, value=15000, step=1000)
    progress = min(saved / target, 1.0) if target > 0 else 0
    st.progress(progress)
    st.write(f"{progress*100:.1f}% of the way to your **{goal_name}** goal (₹{saved:,} / ₹{target:,})")
